const data = [
  {
    "Mileage": "19.07 to 21.47 kmpl",
    "img_url": "https://images.carandbike.com/car-images/colors/volvo/xc90/volvo-xc90-pine-grey.png?v=1638343974",
    "Fuel": "Petrol",
    "id": 1,
    "name": "volvo",
    "avg_horsepower": 285.28,
    "avg_price": 5.25,
    "price": "4.49 - 5.83 Lakh",
    "title": "Volvo XC40",
    "seat": "5 Seater",
    "engine": '1225 cc',
    "desc": "This is the Volvo XC40 T4 R-Design, the petrol derivative of the company's entry-level luxury SUV. And this one comes packed with a BS6 2.0L petrol heart that is available only in the top-spec R-Design trim"
  },
  {
    "Mileage": "17.87 to 18.47 kmpl",
    "img_url": "https://cdni.autocarindia.com/Utils/ImageResizer.ashx?n=http://cms.haymarketindia.net/model/uploads/modelimages/X5ModelImage.jpg&w=730&h=484&q=75&c=1",
    "Fuel": "Petrol & Diesel",
    "id": 2,
    "name": "bmw",
    "avg_horsepower": 379.22,
    "avg_price": 8.22,
    "price": "8.35 - 9.49 Lakh",
    "title": "BMW X7",
    "seat": "5 Seater",
    "engine": '2450 cc',
    "desc": 'The BMW X7 is the brand new flagship SUV from the German automaker and features a new design language and more importantly, the biggest kidney grille ever seen on any BMW product ever!'

  },
  {
    "Mileage": "18.44 to 19.45 kmpl",
    "img_url": "https://d3ced8k77tk9bs.cloudfront.net/6d928d081eef18152206c931033274c8bc378747/1643638401/images/uploads/2020-03-09-GM-GMC-ListingImage-AcadiaAT4.png",
    "Fuel": "Petrol & Diesel",
    "id": 3,
    "name": "gmc",
    "avg_horsepower": 292.33,
    "avg_price": 10.50,
    "price": "9.35 - 12.9 Lakh",
    "title": "Yukon’s Exterior",
    "seat": "6 Seater",
    "engine": '2350 cc',
    "desc": "The Yukon’s exterior was made to stand out. While the SLE and SLT vary slightly in appearance, what they share in common are the bold Yukon grille, LED headlamps and taillamps with GMC signature C-shaped design, and a multitude of available premium wheel options."
  },
  {
    "Mileage": "16.75 to 18.60 kmpl",
    "img_url": "https://cars.usnews.com/static/images/Auto/izmo/i159614629/2022_subaru_ascent_angularfront.jpg",
    "Fuel": "Petrol & Diesel",
    "id": 4,
    "name": "subaru",
    "avg_horsepower": 192.14,
    "avg_price": 7.85,
    "price": "6.35 - 9.49 Lakh",
    "title": "Subaru Impreza",
    "seat": "5 Seater",
    "engine": '2222 cc',
    "desc": "The Subaru Impreza has 1 Petrol Engine on offer. The Petrol engine is 2122 cc . It is available with Manual transmission.Depending upon the variant and fuel type the Impreza has a mileage of . The Impreza is a 5 seater 4 cylinder car and has length of, width of and a wheelbase of ."
  },
  {
    "Mileage": "18.07 to 19.00 kmpl",
    "img_url": "https://images0.cardekho.com/images/car-images/large/Ford/Ford-Endeavour/Smoke-Grey.jpg",
    "Fuel": "Petrol & Diesel",
    "id": 5,
    "name": "ford",
    "avg_horsepower": 281.23,
    "avg_price": 11.48,
    "price": "9.6 - 19.49 Lakh",
    "title": "Ford Aspire",
    "seat": "6 Seater",
    "engine": '1197 cc',
    "desc": "The Ford Aspire has 2 Diesel Engine, 4 Petrol Engine and 1 CNG Engine on offer. The Diesel engine is 1499 cc and 1498 cc, the Petrol engine is 1196 cc and 1194 cc and 1497 cc and 1499 cc while the CNG engine is 1194 cc"
  },
  {
    "Mileage": "28.07 to 29.47 kmpl",
    "img_url": "https://imgd.aeplcdn.com/1200x900/n/cw/ec/47336/e-class-exterior-right-front-three-quarter.jpeg?q=75",
    "Fuel": "Petrol & Diesel",
    "img2":"https://stimg.cardekho.com/images/carexteriorimages/930x620/Mercedes-Benz/GLA/7269/1621948227508/front-left-side-47.jpg",
    "id": 6,
    "name": "mercedes",
    "avg_horsepower": 333.94,
    "avg_price": 8.31,
    "price": "7.86 - 9.10 Lakh",
    "title": "Mercedes-Benz GLA",
    "seat": "5 Seater",
    "engine": '1350 cc',
    "desc": "The Mercedes-Benz GLA has 1 Diesel Engine and 1 Petrol Engine on offer. The Diesel engine is 1950 cc while the Petrol engine is 1332 cc . It is available with Automatic transmission.Depending upon the variant and fuel type the GLA has a mileage of 28.07 to 29.47 kmpl . "
  },
  {
    "Mileage": "22.09 to 24.47 kmpl",
    "img_url": "https://cars.usnews.com/static/images/Auto/izmo/i158929024/2020_audi_a6_angularfront.jpg",
    "Fuel": "Petrol",
    "id": 7,
    "name": "audi",
    "avg_horsepower": 340.59,
    "avg_price": 7.25,
    "price": "6.35 - 9.49 Lakh",
    "title": "Audi A6",
    "seat": "6 Seater",
    "engine": '1500 cc',
    "desc": "The Audi A6 has 1 Petrol Engine on offer. The Petrol engine is 1984 cc . It is available with Automatic transmission.Depending upon the variant and fuel type the A6 has a mileage of 14.11 kmpl & Ground clearance of A6 is 165mm. "
  },
  {
    "Mileage": "20.07 to 11.47 kmpl",
    "img_url": "https://www.traveller.com.au/content/dam/images/h/1/4/w/6/r/image.related.articleLeadwide.620x349.h14u2s.png/1536420837434.jpg",
    "id": 8,
    "Fuel": "Petrol",
    "name": "ram",
    "avg_horsepower": 299.83,
    "avg_price": 6.15,
    "price": "5.39 - 7.10 Lakh",
    "title": "Ram 1500",
    "seat": "5 Seater",
    "engine": '1300 cc',
    "desc": "The redesigned 2019 Ram 1500 is wider than its predecessor, but Ram says it weighs approximately 200 pounds less than the old truck. "
  },
  {
    "Mileage": "18.50 to 19.50 kmpl",
    "img_url": "https://www.mansory.com/sites/default/files/styles/1920x800_fullwidth_car_slider/public/2021-07/mansory-rolls-royce-ghost-my-2021-01.jpg?itok=-aQ6nXpw",
    "Fuel": "Petrol & Diesel",
    "id": 9,
    "name": "rolls-Royce",
    "avg_horsepower": 518.16,
    "avg_price": 99.35,
    "price": "6.95 - 7.95 Cr",
    "title": "Rolls-Royce Ghost",
    "seat": "5 Seater",
    "engine": '1197 cc',
    "desc": "The Rolls-Royce Ghost has 1 Petrol Engine on offer. The Petrol engine is 6750 cc . It is available with Automatic transmission.Depending upon the variant and fuel type the Ghost has a mileage of 6.33 kmpl . The Ghost is a 5 seater 12 cylinder car and has length of 5627mm"
  },
  {
    "Mileage": "15.70 to 18.40 kmpl",
    "img_url": "https://s.aolcdn.com/commerce/autodata/images/USC70PRC014A021001.jpg",
    "Fuel": "Petrol",
    "id": 10,
    "name": "porsche",
    "avg_horsepower": 475.25,
    "avg_price": 99.99,
    "price": "1.69 - 3.08 Cr",
    "title": "Porsche 911",
    "seat": "5 Seater",
    "engine": '1197 cc',
    "desc": "The Porsche 911 has 2 Petrol Engine on offer. The Petrol engine is 2981 cc and 3996 cc . It is available with Manual & Automatic transmission.Depending upon the variant and fuel type the 911 has a mileage of & Ground clearance of 911 is 109."
  },
  {
    "Mileage": "18.07 to 19.47 kmpl",
    "img_url": "https://media.zigcdn.com/media/content/2020/Sep/zw-old-honda-city-1.png",
    "Fuel": "Petrol & Diesel",
    "id": 11,
    "name": "honda",
    "avg_horsepower": 190.62,
    "avg_price": 5.55,
    "price": "5.39 - 7.10 Lakh",
    "title": "Honda City",
    "seat": "5 Seater",
    "engine": '1607 cc',
    "desc": "The Honda City 4th Generation has 1 Petrol Engine on offer. The Petrol engine is 1497 cc . It is available with Manual transmission.Depending upon the variant and fuel type the City 4th Generation has a mileage of 17.4 kmpl & Ground clearance of City 4th Generation is 165mm."
  },
  {
    "Mileage": "24.07 to 25.47 kmpl",
    "img_url": "https://s.aolcdn.com/commerce/autodata/images/USD10CRC131A021001.jpg",
    "Fuel": "Petrol",
    "id": 12,
    "name": "chrysler",
    "avg_horsepower": 291.33,
    "avg_price": 8.27,
    "price": "6.35 - 9.49 Lakh",
    "title": "Chrysler 300",
    "seat": "5 Seater",
    "engine": '1200 cc',
    "desc": "Model year 2015 brought another redesign. While it represents a vast improvement over the 2011 model, the 200 continues to trail the field by a considerable margin."
  }

]


export default data